[build]
  publish = "."

[[redirects]]
  from = "https://findmybreakfast.club/*"
  to = "https://breakfastclubbing.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.findmybreakfast.club/*"
  to = "https://breakfastclubbing.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://breakfastclubbing.com/*"
  to = "https://breakfastclubbing.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.breakfastclubbing.com/*"
  to = "https://breakfastclubbing.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
