name: Club update
description: Add or correct Breakfast Club details
title: "Club update: "
labels:
  - data-update
body:
  - type: input
    id: club_name
    attributes:
      label: Club name
      placeholder: "New York - Williamsburg"
    validations:
      required: true

  - type: checkboxes
    id: update_type
    attributes:
      label: Update type
      options:
        - label: Venue/location
        - label: Host/co-host
        - label: Instagram/LinkedIn links
        - label: Cadence/day schedule
        - label: Other

  - type: textarea
    id: details
    attributes:
      label: Exact details to update
      placeholder: "What should be changed?"
    validations:
      required: true

  - type: textarea
    id: source_links
    attributes:
      label: Source links
      placeholder: "Google Sheet row, newsletter issue, host confirmation"
    validations:
      required: true
